"""The prose guard: no document may describe a practice this code no longer has.

`test_rule_seven.py` guards the numbers — nothing is quoted that has no line in the paper.
This file guards the *claims around* them, which is where the drift actually happened.

When centring was removed from `phi` on 2026-09-02, the code changed in one place and the
prose did not change in four: `cut.py` and `engine.py` each described the read as centring
the block, and the findings record carried both a whole section asserting it and head
counts measured under it presented as a live difference against mantle. Every one of those
was in the present tense, and every one of them read as current fact. Tests passed
throughout, because no test read prose.

That is the failure mode this file exists for. A removed practice explained in the present
tense is worse than no explanation: it is a confident, wrong answer to the exact question a
reader has, and it survives every test a numerical suite can run.

The banned strings below are deliberately narrow. Each names a practice the code does not
have, in the tense that asserts it does. Historical statements are allowed and necessary —
"until 2026-09-02 the library centred the block" is how a reader learns why the conformance
test exists — so each rule carries the contexts that exempt a line.
"""
from __future__ import annotations

import pathlib
import re

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]

#: Directories a reader never sees.
SKIP = {".git", ".pytest_cache", "__pycache__", "build", "dist", ".ruff_cache", "node_modules"}

#: Files this repository does not own, and the outstanding work each represents. A guard that
#: fails on a file nobody here may change is a guard that gets switched off rather than obeyed,
#: so these are exempt --- and this comment is the record that they are not clean.
#:
#: ``AGENTS.md`` is maintained outside this repository. It describes ``phi`` as centred and
#: cites ``bench_kv_recall``, neither of which this tree has any more.
#:
#: ``CLA.md``, ``COMMERCIAL_LICENSE.md``, ``LICENSE`` and ``NOTICE`` are generated by
#: ``agience-cloud/deploy/license_docs.py`` and are deliberately NOT exempt. They named the
#: product "Entroptics Cut" until 2026-09-02; the generator's table now says "Entroptics LLM"
#: and the four were re-rendered from it. Scanning them here is what catches a regeneration
#: that reintroduces the old name --- which matters more than usual, because a commercial
#: licence naming a product the package is not would be a defect in a legal document.
OWNED_ELSEWHERE = {"AGENTS.md"}

#: (what it must not say, why it is banned, what makes an occurrence historical and fine)
RULES = [
    (
        r"cent[re]{2}s the block|centers the block|occupancy centres|phi centres",
        "`phi` reads the block AS RECORDED. Centring was removed on 2026-09-02 because a "
        "constant level is a mode, and on real retrieval horizons subtracting it doubled "
        "the head count (0.319 as recorded against 0.609 centred).",
        (r"until\s+(today|2026)", r"still centred", r"was removed", r"had centred"),
    ),
    (
        r"\bbeacon[_-]llm\b|beacon-surface|beacon_attention",
        "The proof of concept is not a dependency, is not imported, and is not named here. "
        "`mantle.search.beacon` is a different thing -- a real importable module path the "
        "conformance test passes to `importorskip` -- and is allowed.",
        (),
    ),
    (
        r"\bentroptics[_\- ]cut\b",
        "The package is `entroptics_llm`. A stale name in prose sends a reader to an "
        "import that does not exist.",
        (),
    ),
    (
        r"\.attention\b|entroptics_llm\.attention|kv_cut|kv_cache_adapter|bench_kv_|"
        r"bench_grounding|bench_rank_instrument|bench_repair|"
        r"research/negatives",
        "These modules and benchmarks were removed when the package was narrowed to its "
        "claim. A pointer to a file that is not in the tree is a dead end for a reader and "
        "an unreproducible citation for a number.",
        (),
    ),
]


#: Suffixes a reader actually reads. `LICENSE` and `NOTICE` carry no suffix, and carried the
#: stale product name for exactly that reason: nothing was reading them.
READ_BY_HUMANS = {".md", ".py", ".toml", ".cff", ".yml", ".yaml"}
UNSUFFIXED = {"LICENSE", "NOTICE"}

def documents():
    """Every file a reader of this repository can read: prose, code and metadata."""
    for p in sorted(ROOT.rglob("*")):
        if not p.is_file() or set(p.parts) & SKIP or p.name in OWNED_ELSEWHERE:
            continue
        if p.suffix.lower() in READ_BY_HUMANS or p.name in UNSUFFIXED:
            yield p


DOCS = list(documents())


def offending_lines(path, pattern, exemptions):
    """Lines matching `pattern` that no exemption excuses. Case-insensitive throughout."""
    out = []
    for n, line in enumerate(path.read_text(encoding="utf8").splitlines(), 1):
        if not re.search(pattern, line, re.I):
            continue
        if any(re.search(x, line, re.I) for x in exemptions):
            continue
        out.append((n, line.strip()))
    return out


@pytest.mark.parametrize("path", DOCS, ids=lambda p: p.relative_to(ROOT).as_posix())
@pytest.mark.parametrize("pattern,why,exemptions", RULES, ids=lambda v: None)
def test_no_document_describes_a_practice_this_code_does_not_have(path, pattern, why,
                                                                  exemptions):
    # This file necessarily quotes every banned string in order to ban it.
    if path.name == "test_prose_does_not_drift.py":
        pytest.skip("the rule file names what it forbids")
    hits = offending_lines(path, pattern, exemptions)
    assert not hits, (
        f"{path.relative_to(ROOT).as_posix()} says something that is no longer true:\n"
        + "\n".join(f"  line {n}: {t}" for n, t in hits)
        + f"\n\n{why}\n\nEither state it in the past tense with the date, or remove it."
    )


def test_the_guard_can_actually_fail():
    """A guard that cannot fail is decoration.

    Every rule above is checked against a line that must trip it and a line that must not,
    so a regex loosened into uselessness -- or an exemption widened until it excuses
    everything -- turns this red rather than passing quietly over a real drift.
    """
    cases = [
        (0, "the read here centres the block before decomposing", True),
        (0, "until 2026-09-02 the library centred the block", False),
        (0, "the block is read as recorded; nothing is subtracted", False),
        (1, "from beacon_llm.core import lock", True),
        (1, "mantle.search.beacon.engine is the numpy-only implementation", False),
        (2, "import entroptics_cut as e", True),
        (2, "# Contributing to Entroptics Cut", True),
        (2, "import entroptics_llm as e", False),
        (3, "see research/benchmarks/bench_kv_recall.py", True),
        (3, "see research/benchmarks/bench_injection.py", False),
    ]
    for idx, line, should_trip in cases:
        pattern, _, exemptions = RULES[idx]
        tripped = bool(re.search(pattern, line, re.I)) and not any(
            re.search(x, line, re.I) for x in exemptions
        )
        assert tripped is should_trip, (
            f"rule {idx} {'missed' if should_trip else 'wrongly flagged'}: {line!r}"
        )
